name: CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
  schedule:
  - cron: 0 4 * * *
jobs:

  lint:
    name: Linter
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Cache pre-commit hooks
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|py3.10|${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Cache PyPI
      uses: actions/cache@v3
      with:
        key: pip-lint-${{ hashFiles('requirements/*.txt') }}
        path: ~/.cache/pip
        restore-keys: |
          pip-lint-
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: requirements/dev.txt
    - name: Run linters
      run: |
        make lint
      env:
        CI_LINT_RUN: 1
